#
# Netlify config for Kraken real-time alerts (BTC-only)
# Fix: build runs from repo root, cd into app subdir; publish correct dist; functions at repo root
[build]
  command = "cd apps/realtime-alerts && npm install --no-audit --no-fund && npm run build"
  publish = "apps/realtime-alerts/dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = []

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
