# Build-free static site
[build]
  command = ""
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self'; connect-src 'self' https://api.kraken.com wss://ws.kraken.com; img-src 'self' data:; style-src 'self'; frame-ancestors 'none'"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    Referrer-Policy = "no-referrer"
    X-Content-Type-Options = "nosniff"
