[build]
  command = "npm install --no-audit --no-fund && npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

[[redirects]]
  from = "/manifest.json"
  to = "/manifest.json"
  status = 200

[[redirects]]
  from = "/favicon.ico"
  to = "/favicon.ico"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self'; connect-src 'self' https: wss://ws.kraken.com; img-src 'self' data:; style-src 'self' 'unsafe-inline'; frame-ancestors 'none'; base-uri 'self'"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    Referrer-Policy = "no-referrer"
    X-Content-Type-Options = "nosniff"