[build]
  base = "apps/realtime-alerts"
  command = "npm ci --no-audit --no-fund && npm run build"
  publish = "dist"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self'; connect-src 'self' https://api.kraken.com wss://ws.kraken.com; img-src 'self' data:; style-src 'self'; frame-ancestors 'none'"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    Referrer-Policy = "no-referrer"
    X-Content-Type-Options = "nosniff"
