# Netlify config for Kraken real-time alerts (BTC-only)

[build]
  command = "cd apps/realtime-alerts && npm install --no-audit --no-fund && npm run build"
  publish = "apps/realtime-alerts/dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = []

[build.environment]
  NODE_VERSION = "18"

# Optional friendly proxy for functions:
# Call your function as /api/telegram instead of /.netlify/functions/telegram
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
