[build]
  base = "apps/realtime-alerts"
  publish = "dist"
  command = "npm install --no-audit --no-fund && npm run build"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self'; connect-src 'self' wss://ws.kraken.com https:; img-src 'self' data:; style-src 'self' 'unsafe-inline'; frame-ancestors 'none'"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    Referrer-Policy = "no-referrer"
    X-Content-Type-Options = "nosniff"
